config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :facilities do
    resources :rooms, shallow: true do
      resources :availabilities, shallow: true
    end
  end

  resources :users, only:   [:new, :create, :edit, :update]
  resource  :session, only: [:new, :create, :destroy]

  resources :courses
  post 'courses/:id/drop', to: 'courses#drop', as: :drop_course
  post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll_course

  # get('/', {to: 'welcome#index', as: 'root'}) #created this welcome app just to test login and sign up

end

app/models/facility.rb
class Facility < ApplicationRecord
    #Association
    belongs_to :user
    has_many :rooms, dependent: :destroy


    # Validations
    validates(:name, presence: true, uniqueness: true, case_sensitive: false)
    validates(:description, presence: true)
    validates(:address, presence: true)
    validates(:city, presence: true)
    validates(:contact_number, presence: true)

    # Custom methods
    def self.search_by(search_term)
        where("LOWER(city) LIKE :search_term", search_term: "%#{search_term.downcase}%")
    end

end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_facility, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, except: [:index, :create, :show, :new]

    def new
        @facility = Facility.new
    end

    def create 
        @facility = Facility.new facility_params
        @facility.user = current_user
        if @facility.save
            flash[:notice] = 'Facility Created Successfully'
            redirect_to @facility
        else
            render :new
        end
    end 


    def index 
        if current_user.is_manager?
            user = current_user
            @facilities = user.facilities
        elsif params[:search]
            @search_term = params[:search]
            @facilities = Facility.search_by(@search_term)
        else
            @facilities = Facility.order(created_at: :DESC)
        end
        
    end 

    def show
        if can? :crud, @facility
        @room = Room.new
        end
        # if params[:search]
        #     @search_term = params[:search]
        #     @rooms = Room.search_by(@search_term)
        # else
            @rooms = @facility.rooms.order(created_at: :desc)
        # end
    end

    def edit
    end

    def update
        if @facility.update facility_params
            redirect_to facility_path(@facility)
        else
            render :edit
        end
    end 

    def destroy
        @facility.destroy
        redirect_to facilities_path
    end 


    private 

    def facility_params
        params.require(:facility).permit(:name, :description, :address, :city, :postal_code, :contact_number, :parking)
    end

    def find_facility
        @facility = Facility.find params[:id]
    end

    def authorize!
        redirect_to root_path, alert: "access denied" unless can? :crud, @facility
    end

end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<div class="box">
 <section>
<%= form_with model: @facility, local: true do |f| %>
  <% if @facility.errors.any? %>
   <ul>
    <% @facility.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end  %>
  </ul> 
  <% end %>
  <div>
       <%= f.text_field :name, placeholder: "name" %>
  </div>
  <div>
    <%= f.text_area :description, placeholder: "description" %>
  </div>
  <div>
   
    <%= f.text_field:address, placeholder: "address" %>
  </div>
  <div>
    <%= f.text_field :city, placeholder: "city" %>
  </div>
  <div>
    
    <%= f.text_field :contact_number, placeholder: "contact_number" %>
  </div>
  <div>
  
    <%= f.check_box :parking, placeholder: "parking" %>
  </div>
  <%= f.submit %>
<% end %>

</section>
</div>

app/views/facilities/edit.html.erb
<h1>Edit Facility</h1>
<%= render 'form' %>

app/views/facilities/index.html.erb
<% if current_user.is_manager %>
  <h1>My Facilities</h1>
<% else %>
  <h1>Facilities</h1>
<% end %>

<h2>Filter by City:</h2>

<%= form_for "", url: facilities_path, role: "search", method: :get do %>
    <p>
        <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
        <%= submit_tag "Search", :city => nil %>
    </p>
<% end %>

<% @facilities.each do |facility|  %>
  <ul>
    <li><%= link_to facility.name, facility_path(facility) %></li>
  </ul>
<% end %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

app/views/facilities/show.html.erb
<div class="alert alert-primary" role="alert">

<div class="card" style="width: 18rem;">
  <div class="card-header">
    <h1><%= @facility.name %></h1>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><p>Description: <%= @facility.description %></p></li>
    <li class="list-group-item"><p>Address: <%= @facility.address %>  </p></li>
    <li class="list-group-item"><p>City:  <%= @facility.city %>  </p></li>
    <li class="list-group-item"><p>Contact:  <%= @facility.contact_number %>  </p></li>
  </ul>
</div>

  
</div>





  <% if @facility.parking? %>  
    <p>Parking: Yes</p>
  <% else %>
    <p>Parking: No</p>
  <% end%>

<% if can? :crud, @facility %>
  <button type="button" class="btn btn-danger">  <%= link_to 'Delete', facility_path(@facility), method: :delete, data: { confirm: 'Are you sure that you want to delete this facility?' } %>
  </button>  
        
  <button type="button" class="btn btn-success"> <%= link_to "Edit", edit_facility_path(@facility) %> </button>

  <button type="button" class="btn btn-primary"><%= link_to "Create a Room", new_facility_room_path(@facility) %></button> 
<% end %>

<h2>Filter Rooms by Feature:</h2>

<%= form_for "", url: @facility, role: "search", method: :get do %>
    <p>
        <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
        <%= submit_tag "Search", :one_hour_rental_price => nil %>
    </p>
<% end %>



<h1>Rooms</h1>
 <% @rooms.each do |room|  %>
  <ul>
    <li><%= link_to "#{room.name}", room_path(room) %></li>
  </ul>
<% end %>