config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :facilities do
    resources :rooms, shallow: true do
      resources :availabilities, shallow: true
    end
  end

  resources :users, only:   [:new, :create, :edit, :update]
  resource  :session, only: [:new, :create, :destroy]

  resources :courses
  post 'courses/:id/drop', to: 'courses#drop', as: :drop_course
  post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll_course

  # get('/', {to: 'welcome#index', as: 'root'}) #created this welcome app just to test login and sign up

end

app/models/room.rb
class Room < ApplicationRecord
    
    # Call Backs
    before_validation :set_default_value_price
    belongs_to :facility
    has_many :availabilities, dependent: :destroy

    # Validations
    validates(:name, presence: true, case_sensitive: false)
    validates(:capacity, presence: true, numericality: { greater_than_or_equal_to: 0 } )
    validates(:area, presence: true)
    validates(:one_hour_rental_price, presence: true, numericality: { greater_than: 0 })

    # Custom methods
    # def self.search_by(search_term)
    #     where("LOWER(one_hour_rental_price) LIKE :search_term", search_term: "%#{search_term}%")
    # end

    private

    def set_default_value_price
        self.one_hour_rental_price ||= 300
    end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index, :search]
    before_action :find_room, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]

    
    def new
        @room = Room.new
    end 

    def index
        if params[:search]
            @search_term = params[:search]
            @rooms = Room.search_by(@search_term)
        else
            @rooms= Room.order(created_at: :DESC)
        end
    end

    def search

    end

    def show
        @availability = Availability.new
        @availabilities = Availability.all
    end

    def create
        @facility = Facility.find(params[:facility_id])
        @room = Room.new room_params
        @room.facility = @facility
        # @room.user_id = 1
        if @room.save
          redirect_to @facility
        else
          @rooms = @facility.rooms.order(created_at: :desc)
          render 'facilities/show'
        end
    end

    def edit
        render :edit
    end

    def update
        if @room.update room_params
            redirect_to room_path(@room)
        else
            render :edit
        end
    end 

    def destroy
        @room.destroy
        redirect_to facilities_path
    end 


    private

    def find_room
        @room = Room.find params[:id]
    end
    
    def room_params
        params.require(:room).permit(:capacity, :area, :whiteboard, :internet, :name)
    end

    def authorize!
        redirect_to room_path(@room), alert: "access denied" unless can? :crud, @room
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%#= form_with model: @rooms, local: true do |f| %>
<%= form_for @room, url: {action: "create"}, local: true do |f| %>

  <% if @room.errors.any? %>
   <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end  %>
  </ul> 
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :capacity %>
    <%= f.text_field :capacity %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>
  <div>
    <%= f.label :whiteboard %>
    <%= f.check_box :whiteboard %>
  </div>
  <div>
    <%= f.label :internet %>
    <%= f.check_box :internet %>
  </div>
   <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div>
    <%= f.label :one_hour_rental_price %>
    <%= f.number_field :one_hour_rental_price %>
  </div>
  <%= f.submit %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<%= form_with model: @rooms, local: true do |f| %>

  <% if @room.errors.any? %>
   <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end  %>
  </ul> 
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :capacity %>
    <%= f.text_field :capacity %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>
  <div>
    <%= f.label :whiteboard %>
    <%= f.check_box :whiteboard %>
  </div>
  <div>
    <%= f.label :internet %>
    <%= f.check_box :internet %>
  </div>
   <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div>
    <%= f.label :one_hour_rental_price %>
    <%= f.number_field :one_hour_rental_price %>
  </div>
  <%= f.submit %>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

app/views/rooms/show.erb
<h1> <%= @room.name %> </h1>

<% if @room.image_url != "" %>
    <%= image_tag "#{@room.image_url}", alt: 'room-image', class: 'room-image' %>
<% end %>

<p> Capacity: <%= @room.capacity %> people</p>

<p> Area: <%= @room.area %> </p>

<% if @room.whiteboard == true %>
    <p> Whiteboard: Yes </p>
<% end%>

<% if @room.internet == true %>
    <p> Internet: Yes </p>
<% end %>

<p> Price per hour: $<%= @room.one_hour_rental_price %> </p>

<% if can? :crud, @room %>
  <%= link_to 'Delete', room_path(@room), method: :delete, data: { confirm: 'Are you sure that you want to delete this room?' } %>
  <%= link_to "Edit", edit_room_path(@room) %>
<% end %>
<br>
<%= month_calendar events: @availabilities do |date, availabilities| %>
  <%= date %>

  <% availabilities.each do |availability| %>
    <div>
      <%= availability.start_date %>
      <%= availability.end_date %>
      <%= availability.start_time %>
      <%= availability.end_time %>
    </div>
  <% end %>
<% end %>
<hr />


<% if can? :crud, @room %>
    <%= form_with model: [@room, @availability], local: true do |f| %>
        <% if @availability.errors.present? %>
        <ul>
            <% @availability.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <%end  %>
        </ul> 
        <% end %>
        <div>
            <%= f.label :start_date %>
            <%= f.text_field :start_date %>
        </div>
        <div>
            <%= f.label :end_date %>
            <%= f.text_field :end_date %>
        </div>
        <div>
            <%= f.label :start_time %>
            <%= f.text_field :start_time %>
        </div>
        <div>
            <%= f.label :end_time %>
            <%= f.text_field :end_time %>
        </div>

        <%= f.submit %>
    <% end %>
<% end %>