config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :facilities do
    resources :rooms, shallow: true do
      resources :availabilities, shallow: true
    end
  end

  resources :users, only:   [:new, :create, :edit, :update]
  resource  :session, only: [:new, :create, :destroy]

  resources :courses
  post 'courses/:id/drop', to: 'courses#drop', as: :drop_course
  post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll_course

  # get('/', {to: 'welcome#index', as: 'root'}) #created this welcome app just to test login and sign up

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course, only: [:edit,:update,:show, :destroy, :drop, :enroll]
  before_action :authorize!, only: [:edit, :update, :destroy]

  def enroll
    enrollment = current_user.enrollments.where(course_id: @course.id)
    if enrollment.empty?
      current_user.enrollments.create(course_id: @course.id, status: "Enrolled")
    else
      puts "Course enrollment updated"
      enrollment.update ({status: "Enrolled"})
    end
    flash[:notice] = 'Course Enrolled Successfully'
    redirect_to @course
  end

  def drop
    enrollment = current_user.enrollments.where(course_id: @course.id)
    enrollment.update ({status: "Pending"})
    flash[:notice] = 'Course Dropped Successfully'
    redirect_to @course
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    @course.user = current_user
    if @course.save
      flash[:notice] = 'Course Created Successfully'
      redirect_to @course
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update    
    if @course.update course_params
      flash[:notice] = 'Course Updated Successfully'
      redirect_to @course
    else
      render :edit
    end
  end

  def index
    if current_user.is_admin
      @courses = Course.order(created_at: :desc)
    elsif current_user.is_teacher
      @courses = Course.where(user_id: current_user.id).order(created_at: :desc)
    elsif current_user.is_student
      @courses = current_user.enrolled_courses
      @open_courses = Course.where(status: "Open").order(created_at: :desc)
    end
  end

  def show

  end

  def destroy
    @course.destroy
    flash[:notice] = 'Course Updated Successfully'
    redirect_to courses_path
  end
  
  private

  def find_course
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit(:title, :description, :status, :tuition, :capacity, :image_url)
  end

  def authorize! 
    unless can?(:crud, @course)
      redirect_to root_path, alert: 'Not Authorized' 
    end
  end
end

app/views/courses/_form.html.erb
  <div class="box">
 <section>
  <%= form_with(model: @course, local: true) do |form| %>
    <div>
      <% if @course.errors.present? %>
        <%= @course.errors.full_messages.join(', ') %>
      <% end %>
    </div>
    <div>
      
      <%= form.text_field :title, value: @course.title , placeholder: "title" %>
    </div>
    <div>
      
      <%= form.text_area :description, cols: 50, rows: 5, value: @course.description, placeholder: "description"  %>
    </div>
    <div>

      <%= form.text_field :status, value: @course.status , placeholder: "status" %>
    </div>
    <div>

      <%= form.text_field :tuition, value: @course.tuition, placeholder: "tuition" %>
    </div>
    <div>
     
      <%= form.text_field :capacity, value: @course.capacity, placeholder: "capacity" %>
    </div>    
    <div>
      <%= form.text_field :image_url, value: @course.image_url, placeholder: "image_url" %>
    </div>    
    <%= form.submit %>
  <% end %>

  </section>
</div>

app/views/courses/edit.html.erb
<h1>Edit Course Form</h1>
<%= render 'form' %>

app/views/courses/index.html.erb
<h1>My Courses</h1>
<% @courses.each do |course| %>
  <div>
    <h3><%= link_to(course.title, course_path(course.id)) %></h3>
    <p><%= course.description %></p>
    <p>Status: <%= course.status %></p>
    <p>Tuition: <%= course.tuition %></p>
    <p>Capacity: <%= course.capacity %></p>
    <small>
      <p line-height="normal">
        Posted <%= time_ago_in_words(course.created_at) %> ago
      </p>
    </small>
  </div>
<% end %>
<% if current_user.is_student %>
  <h1>Other Open Courses</h1>
  <% @open_courses.each do |course| %>
    <div>
      <h3><%= link_to(course.title, course_path(course.id)) %></h3>
      <p><%= course.description %></p>
      <p>Status: <%= course.status %></p>
      <p>Tuition: <%= course.tuition %></p>
      <p>Capacity: <%= course.capacity %></p>
      <small>
        <p line-height="normal">
          Posted <%= time_ago_in_words(course.created_at) %> ago
        </p>
      </small>
    </div>
  <% end %>
<% end %>

<% if current_user.is_teacher %>
  <h3><%= link_to "Create New Course", new_course_path %></h3>
  <h3><%= link_to "Find a Facility to Book a Classroom", facilities_path %></h3>
<% end %>

app/views/courses/new.html.erb
<h1>New Course Form</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1>Course</h1>
<h3><%= @course.title %></h3>
<p><%= @course.description %></p>
<p>Status: <%= @course.status %></p>
<p>Tuition: <%= @course.tuition %></p>
<p>Capacity: <%= @course.capacity %></p>
<small>
  <p line-height="normal">
    Posted <%= time_ago_in_words(@course.created_at) %> ago<br>
  </p>
</small>
<% if can? :edit, @course %>
  <button type="button" class="btn btn-success"><%= link_to 'Edit', edit_course_path(@course.id)%>
  </button>
<% end %>
<% if can? :destroy, @course %>
  <button type="button" class="btn btn-danger">  <%= link_to("Delete", course_path(@course), method: :delete, data:{confirm:'Delete Course?' }) %>
  </button>
<% end %>
<% if current_user.is_student %>
  <% if current_user.enrolled_courses&.include?(@course) && current_user.enrollments.where(course_id: @course.id).where(status: "Enrolled").count > 0 %>
    <%= link_to("Drop", drop_course_path(@course), method: :post, data:{confirm:'Drop Course Enrollment?' }) %>
  <% else %>
    <%= link_to("Enroll", enroll_course_path(@course), method: :post, data:{confirm:'Enroll Course?' }) %>
  <% end %>
<% end %>