config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :facilities do
    resources :rooms, shallow: true do
      resources :availabilities, shallow: true
    end
  end

  resources :users, only:   [:new, :create, :edit, :update]
  resource  :session, only: [:new, :create, :destroy]

  resources :courses
  post 'courses/:id/drop', to: 'courses#drop', as: :drop_course
  post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll_course

  # get('/', {to: 'welcome#index', as: 'root'}) #created this welcome app just to test login and sign up

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <header>
    <title>Room2Spare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <a href="#">
      <%=  image_tag 'chrome.png', class:'logo', alt:'logo'%>
      <strong>Room2Spare</strong>
    </a>
  </header>

  <body>
  <nav class="navbar navbar-dark bg-primary">

      <% if user_signed_in? %>
          Hello  <%=link_to(current_user.first_name, edit_user_path(current_user)) %>,
          <%= link_to 'Home', root_path %>
          <%= link_to "Log out", session_path, method: :delete,
          data: {confirm: "Are you sure you want to log out?"} %>
          <% if current_user.is_manager %>
            <%= link_to "My Facilities", facilities_path %>
          <% end %>
          <% if current_user.is_teacher %>
            <%= link_to "My Courses", courses_path %>
            <%= link_to "My Bookings", courses_path %>
          <% end %>
          <% if current_user.is_student %>
            <%= link_to "My Courses", courses_path %>
          <% end %>
      <% else %>
      

        <%= link_to "Login" , new_session_path %>
  
        <%= link_to "Sign Up", new_user_path %>
        
      <% end %>
      </nav>
      <% flash.each do |type, message| %>
      <div class="alert alert-info">
        <%= message %>
      </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <script src="http://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="http://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
<div class="container"> <% yield %>

</div>
<script src="http://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="http://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>